### ISSUE TITLE
Build flask docs failed: ImportError: cannot import name 'DocVersion'

### ISSUE THREAD

**Issue by garenchan** [pallets/pallets-sphinx-themes#15]
## Environment
``flask``: master branch
``pallets-sphinx-themes``: v1.1.1

## Error1
```
Traceback (most recent call last):
  File "e:\python 3.5\lib\site-packages\sphinx\config.py", line 161, in __init__
    execfile_(filename, config)
  File "e:\python 3.5\lib\site-packages\sphinx\util\pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "conf.py", line 7, in <module>
    from pallets_sphinx_themes import DocVersion, ProjectLink, get_version
ImportError: cannot import name 'DocVersion'
```

## Reason

Since ``pallets-sphinx-themes`` version 1.1.0, ``DocVersion`` api has not been exposed but also not deprecated.

## Error2

When I solved the above problem, another error occurred. 
```
Theme error:
no theme named 'flask' found (missing theme.conf?)
```

## Reason

1. ``flask`` docs' ``conf.py`` doesn't add ``pallets-sphinx-themes`` into its extensions

2. ``pallets-sphinx-themes`` doesn't add ``sphinx.html_themes`` entry points.

**Comment by garenchan** [comment]
https://github.com/pallets/flask/pull/2898#issuecomment-417816155

**Comment by davidism** [comment]
This is intentional. If you want to use `DocVersion` manually, import it using the full path. The other error is also intentional, add `pallets-sphinx-themes` to the extensions.
