### ISSUE TITLE
Extension error: Unknown event name: autodoc-skip-member

### ISSUE THREAD

**Issue by triangulum** [pallets/pallets-sphinx-themes#18]
Hello!

So I followed the instructions and installed the theme via *pip*.

I then added the following to my `conf.py` file, as requested:

```python
extensions = [
    'pallets_sphinx_themes'
]

html_theme = 'flask'
```

Now, when I run `make clean; make html`, the resulting error is:

```bash
Removing everything under 'build'...
Running Sphinx v1.6.6
making output directory...

Extension error:
Unknown event name: autodoc-skip-member
make: *** [html] Error 1
```

Any insights? I don't have any issues when running any of the default themes...

**Comment by davidism** [comment]
You need to enable the autodoc extension as well.

**Comment by triangulum** [comment]
Thanks! Note: this only works when *sphinx.ext.autodoc* is loaded **before** *pallets-sphinx-themes*.
