### ISSUE TITLE
2.10 is sorting below 2.9

### ISSUE THREAD

**Issue by davidism** [pallets/pallets-sphinx-themes#24]
The Jinja 2.10.x build on Read the Docs is showing "this is an old version, the latest is 2.9.x".

**Comment by davidism** [comment]
Looks like Read the Docs is sorting `html_context["versions"]` alphabetically (after placing master/latest first). This works until you get to versions with 9 and 10.

@davidfischer Does RTD document what order it reports versions in? Should it?

**Comment by davidfischer** [comment]
I'm going to put my comments in https://github.com/readthedocs/readthedocs.org/issues/6010 but we should be able to get this resolved without too much pain.
