### ISSUE TITLE
In sidebar, add links to the reST sources (aka html_show_sourcelink).

### ISSUE THREAD

**Issue by return42** [pallets/pallets-sphinx-themes#32]
This is not really a issue, its more a question ...

I guess [html_show_sourcelink](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-html_show_sourcelink) is not supported by pallets-sphinx-themes .. right?

If so and since the default of html_show_sourcelink is _True_,  is it better to set

     html_show_sourcelink = False

to not copy sources into the dist folder `_sources`? 

What should a PR add, changing the default to _False_ or is it better to implement the function right away?

**Comment by davidism** [comment]
Add `"sourelink.html"` to the `html_sidebars` config. It's part of Sphinx's basic theme and not overridden by this theme.
