### ISSUE TITLE
Search on Flask/Werkzeug/jinja... website is broken (redirect loop)

### ISSUE THREAD

**Issue by soxofaan** [pallets/pallets-sphinx-themes#42]
I'm not sure this is the right place to raise this issue, but the search feature  seems to be broken on the documentation websites of Flask, Werkzeug, Jinja, ...

e.g. if I search for "flask" on the flask doc website: get this result page: 
https://flask.palletsprojects.com/en/2.0.x/search/?q=flask

the first hit is for example "flask (Python module, in API)", linking to url  https://flask.palletsprojects.com/en/2.0.x/search/api/?highlight=flask#module-flask

When I click that link, my browser (Firefox) complains with "The page isn't redirecting properly". In Chromium I get "flask.palletsprojects.com redirected you too many times.". Chromium suggest to clear my cookies, but that does not help.

seems like the page is redirecting to itself:

```
$ curl -I 'https://flask.palletsprojects.com/en/2.0.x/search/api/?highlight=flask#module-flask'
HTTP/1.1 302 Found
...
Location: https://flask.palletsprojects.com/en/2.0.x/search/api/?highlight=flask
...
```

**Comment by davidism** [comment]
Duplicate of #39
