### ISSUE TITLE
dark mode

### ISSUE THREAD

**Issue by jwogrady** [pallets/pallets-sphinx-themes#48]
I am requesting  a dark mode version of the website and documentation. It's not about my personal style preference. It's a usability issue since I am presently dealing with cataracts.

A dark theme can be easier to read because it reduces light and improves contrast. An alternate solution would be having the ability to change the style.

I want to thank you for Flask. It's incredible.

**Comment by yuxiaoy1** [comment]
Hi, I'm working on this feature.
Do we need configuration to enable/disable the dark mode (show/hide the switch)?

**Comment by ThiefMaster** [comment]
I think giving users the option to toggle it (persistently - save it e.g. in localStorage) is enough.

**Comment by yuxiaoy1** [comment]
Got it.
One more question, the `themes/babel` folder is unused, right? I checked the [`conf.py`](https://github.com/python-babel/babel/blob/master/docs/conf.py#L29) of babel, and it didn't involve the `pallets-sphinx-thmes`.

**Comment by davidism** [comment]
We're planning to switch to [Furo](https://pradyunsg.me/furo/) as a base theme, which will provide a dark mode.
