### ISSUE TITLE
2.0.1: DeprecationWarning 

### ISSUE THREAD

**Issue by kloczek** [pallets/pallets-sphinx-themes#50]
Deprecation messages are printed on building `rich` module documemntation.
https://github.com/willmcgugan/rich/issues/1240

**Comment by davidism** [comment]
Please provide details here, not only as a link to another issue.

**Comment by kloczek** [comment]
What is the problem with that link? It does not work for you??

**Comment by ThiefMaster** [comment]
It's nice is issues are self-contained - wouldn't be the first time some projects decides to leave GitHub and turns off their issue tracker, making all existing issues inaccessible.

**Comment by kloczek** [comment]
> It's nice if issues are self-contained - wouldn't be the first time some projects decides to leave GitHub and turns off their issue tracker, making all existing issues inaccessible.

I'm not aware of the possibility of turning such things off.

Please focus on the actual issue.
If you need more details please let me know and I'll try to deliver whatever will be needed ASAP.

**Comment by davidism** [comment]
When you click to read up on an issue, only to see "go here to read about it instead" it can be inconvenient and more confusing for contributors. Always try to make issues as straightforward as possible when opening them.
