### ISSUE TITLE
Change the font for better readability

### ISSUE THREAD

**Issue by greyli** [pallets/pallets-sphinx-themes#57]
The current font is hard to read, and it makes people feel tired when reading for a long time.

Here is a comparison between the current font and a font that has better readability.

The current font:

![flask-font-old](https://user-images.githubusercontent.com/12967000/142220201-7a5bf037-d5a2-4d6a-b044-5d942b3aa656.png)

The font with `Optima, Segoe, "Segoe UI", Candara, Calibri, Arial` (this may not the best font to use, just as an example):

![flask-font-new](https://user-images.githubusercontent.com/12967000/142220399-26cbf12d-4d92-429e-a417-2f867b2e6f1f.png)

**Comment by davidism** [comment]
This is too subjective. I'm fine with the current one. If users have special requirements for fonts, they're probably already using an extension to override styles.
