### ISSUE TITLE
Extension error on sphinx-build: cannot import name pass_context from jinja2

### ISSUE THREAD

**Issue by jwg4** [pallets/pallets-sphinx-themes#59]
Hi, I am trying to add sphinx documentation to my project https://github.com/jwg4/flask-selfdoc (so the documentation is currently totally minimal. I was able to build the docs by running sphinx-build, however after adding "pallets_sphinx_themes" as an extension in `docs/conf.py`, setting the theme to 'flask' and installing pallets-sphinx-themes, I can no longer build the docs, as follows: 

```
jack@yyy:~/flask-selfdoc $ poetry run sphinx-build -b html docs/ docs/_build/html
Running Sphinx v4.4.0

Extension error:
Could not import extension pallets_sphinx_themes (exception: cannot import name 'pass_context' from 'jinja2' (/home/jack/.cache/pypoetry/virtualenvs/flask-selfdoc-vTLo-IC6-py3.8/lib/python3.8/site-packages/jinja2/__init__.py))
```

I'm using Python 3.8.9, the attached `poetry.lock` shows all my dev environment dependencies including sphinx, jinja and this project.

[poetry.lock.txt](https://github.com/pallets/pallets-sphinx-themes/files/8192432/poetry.lock.txt)

I can try and reproduce minimally without all the other packages, but I wanted to check first in case I'm doing something obviously wrong. Thanks!

**Comment by jwg4** [comment]
The repo exactly as it was when I tried to build is at https://github.com/jwg4/flask-selfdoc/tree/sphinx_issue in case it helps anyone

**Comment by davidism** [comment]
You'll need to upgrade Jinja to the latest version, or downgrade the themes to a version that does not use the latest Jinja.

**Comment by jwg4** [comment]
Thanks very much, works now. 

Perhaps the required version of jinja2, or a flask version which requires it, should be a dep of this package?
