### ISSUE TITLE
pallests-sphinx-themes 2.0.2 is not compatible with latest packaging release

### ISSUE THREAD

**Issue by jugmac00** [pallets/pallets-sphinx-themes#66]
see https://github.com/readthedocs/readthedocs.org/issues/9805#issuecomment-1363573399

@davidism is already working on a fix -thanks for that!

**Comment by davidism** [comment]
https://github.com/pallets/pallets-sphinx-themes/commit/4c8b99a7aff00f043030ebc418c4b6d3fd6f622c

2.0.3 is available
