### ISSUE TITLE
Support for Sphinx parallel build

### ISSUE THREAD

**Issue by bluetech** [pallets/pallets-sphinx-themes#88]
I was trying out `sphinx-build -j auto` in the pytest repo to maybe speed up the docs build a bit. It fails with the following error:

> NotImplementedError: merge_domaindata must be implemented in <class 'pallets_sphinx_themes.themes.click.domain.ClickDomain'> to be able to do parallel builds!

Link to [merge_domaindata](https://www.sphinx-doc.org/en/master/extdev/domainapi.html#sphinx.domains.Domain.merge_domaindata).

I haven't been able to complete a `-j` build so I'm not sure if it's actually worth the effort.

**Comment by davidism** [comment]
I'd be happy to consider a PR, but won't have time to work on this myself any time soon.

**Comment by bluetech** [comment]
Yes it's not very clear, but after looking into it, it's meant for `Domain`s which use [`self.data`](https://www.sphinx-doc.org/en/master/extdev/domainapi.html#sphinx.domains.Domain.data), which `ClickDomain` and `JinjaDomain` don't (either directly or indirectly). So the implementation can just be a no-op. I will submit a PR.

BTW, after testing in pytest, `-j4` brings the docs build time from 29s to 23s, so doesn't help that much, but might as well support it.
