### ISSUE TITLE
We're planning to switch to Furo as a base theme, which will provide a dark mode.

### ISSUE THREAD

**Issue by return42** [pallets/pallets-sphinx-themes#97]
> We're planning to switch to [Furo](https://pradyunsg.me/furo/) as a base theme, which will provide a dark mode.

_Originally posted by @davidism in https://github.com/pallets/pallets-sphinx-themes/issues/48#issuecomment-1582583448_
            
Any news? / why has the conversation of #48 been closed and locked as resolved?

**Comment by davidism** [comment]
Still the plan.

**Comment by return42** [comment]
@davidism thanks for feedback .. sorry if I'm annoying :) the fact that PR #48 was closed leaves the impression that either the feature request has been fulfilled or is not planned. Wouldn't it be better to mark the feature request as such and leave it open?  ATM the request is _"closed and locked as resolved"_ .. which forced me to have to open a (superfluous) new issue for a status query.
